-- MySQL Script generated by MySQL Workbench
-- Wed Sep 10 17:31:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sellcar_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sellcar_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sellcar_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sellcar_db` ;

-- -----------------------------------------------------
-- Table `sellcar_db`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcar_db`.`cars` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` BIGINT NULL DEFAULT NULL,
  `transmission` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `year` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sellcar_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcar_db`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `user_role` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sellcar_db`.`bookacar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sellcar_db`.`bookacar` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `book_car_status` TINYINT NULL DEFAULT NULL,
  `days` BIGINT NULL DEFAULT NULL,
  `from_date` DATETIME(6) NULL DEFAULT NULL,
  `price` BIGINT NULL DEFAULT NULL,
  `to_date` DATETIME(6) NULL DEFAULT NULL,
  `car_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK99td0bb44dbrkb0pp4dsuclr3` (`car_id` ASC) VISIBLE,
  INDEX `FKnd922np5sn77khrfqurymq76w` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK99td0bb44dbrkb0pp4dsuclr3`
    FOREIGN KEY (`car_id`)
    REFERENCES `sellcar_db`.`cars` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKnd922np5sn77khrfqurymq76w`
    FOREIGN KEY (`user_id`)
    REFERENCES `sellcar_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
